name: Environments

on:
  workflow_dispatch:

jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deployed on Dev environment"

  Stage:
    runs-on: ubuntu-latest
    needs: Dev
    steps:
      - name: Deploy
        run: echo "Deployed on Staging environment"

  Prod:
    runs-on: ubuntu-latest
    needs: Stage
    steps:
      - name: Deploy
        run: echo "Deployed on Production environment"
